\documentclass[12pt]{article}
\usepackage{longtable}
\usepackage{microtype}
\usepackage[margin=1in]{geometry}
\usepackage[table]{xcolor}
\begin{document}

<<echo=FALSE>>=
library(xtable)
library(lubridate)
info<-read.csv('../out/info.csv',stringsAsFactors=FALSE)
and<-function(x){
  if(length(x)==1)return(x)
  last2<-length(x)-1:0
  x<-c(x[-last2],paste(x[last2],collapse=' and '))
  paste(x,collapse=', ')
}
makeAlign <- function(xx) {
  if(is.data.frame(xx))format <- ifelse(sapply(xx, is.numeric), "r", "l")
  else format <- rep(ifelse(is.numeric(xx),'r','l'),ncol(xx))
  sprintf('|%s|',paste(c("r", format), collapse = "|"))
}
customXtable <- function(xx, ...,printArgs=c()) do.call(print.xtable,c(list(xtable(xx, ..., align = makeAlign(xx)),add.to.row=list(list(-1),'\\rowcolor{gray!5!blue!10}'),size='\\rowcolors{2}{blue!5}{white}'),printArgs))
@
\section{Methods}
Over the course of 4 tagging seasons, 80 pop-up satellite archival tags were deployed by researchers, commercial fishermen and fishery observers.  Combined these tracking data cover 9785 turtle-days. A range of Wildlife Computing \Sexpr{and(unique(info$Tag.Type))} tags were used (Table \ref{tabTagYear}).

<<echo=FALSE,results=tex>>=
customXtable(table(info$Tag.Type,year(info$deployDate)),caption="The types of tags deployed over the 4 tagging seasons",label='tabTagYear')
@


Tag data was [[MIKE: DOWNLOADED FROM WC WEBSITE]] and processed using WC-DAP v3.0.369. Status messages and the minimum and maximum depths reported by WC-DAP were used to infer turtle fate. The tags were programmed to release after a set period, after [[MIKE: X days]] constant depth or reaching a maximum depth threshold to allow transmission of data prior to tag failure.

\section{Results}
Turtle fate:
<<echo=FALSE,results=tex>>=
fate<-info[,c('ptt','hook','deployDate','observer','lastDay','fate')]
fate$hook<-sub('NoHook','No Hook',info$hook)
fate$observer<-sub('Observer','Observer/researcher',info$observer)
fate$fate<-sub('(.+)([A-Z])',' \\1 \\2',fate$fate)
colnames(fate)<-c('PTT','Hook','Deploy date','Deployer','Deploy length','Fate')
customXtable(fate,printArgs=list(tabular.environment='longtable',include.rownames=FALSE,floating=FALSE),caption="\\cellcolor{white}PTT tag IDs, hooking location, deployment date, deployment length and inferred fate for all turtles in the study",label='tabFate')
@

<<echo=FALSE,results=tex>>=
customXtable(table(info$fate,year(info$deployDate)))
@

\section{Conclusions}

\end{document}
