\documentclass[12pt]{article}
\begin{document}

\section{Methods}
Over the course of 4 tagging seasons, 80 pop-up satellite archival tags were deployed by researchers, commercial fishermen and fishery observers.  Combined these tracking data cover 9785 turtle-days.

Tag data was [[MIKE: DOWNLOADED FROM WC WEBSITE]] and processed using WC-DAP v3.0.369. Status messages and the minimum and maximum depths reported by WC-DAP were used to infer turtle fate. The tags were programmed to release after a set period, after [[MIKE: X days]] constant depth or reaching a maximum depth threshold to allow transmission of data prior to tag failure.

\section{Results}
Tag fate per year:

\begin{tabular}{lcccc}
                & 2011 & 2012 & 2014 & 2015 \\ 
  Broken        & 0    & 4    & 0    & 1    \\ 
  ConstantDepth & 0    & 2    & 0    & 0    \\ 
  Float         & 0    & 4    & 18   & 5    \\ 
  Lost          & 1    & 14   & 0    & 0    \\ 
  Scheduled     & 0    & 8    & 1    & 12   \\ 
  StillOn       & 0    & 0    & 0    & 4    \\ 
  TooDeep       & 0    & 2    & 0    & 2    \\ 
  Unknown       & 0    & 2    & 0    & 0    \\ 
\end{tabular}

Tag types per year:

\begin{tabular}{lr}
  MinPAT     &    20\\
  PAT        &    41\\
  PTT SPLASH &     1\\
  SPLASH 323-B&   18\\
\end{tabular}

Tags per year:
  2011    1
  2012   36
  2014   19
  2015   24

Observer/hook type:

\begin{tabular}{lccc}
            Deep Light NoHook\\
  Fisherman &  13 &   14 &     3\\
  NA        &   0 &    0 &     4\\
  Observer  &  25 &   18 &     2\\
\end{tabular}

\section{Conclusions}

\end{document}
