library(survival)
source("~/scripts/R/dna.R")

if(!exists('tagData'))source('readData.R')
info$hookFac<-factor(info$hook)
surv<-Surv(info$lastDay,info$fate %in% c('TooDeep','ConstantDepth'))
survNoNoHook<-Surv(info$lastDay[info$hook!='NoHook'],info$fate[info$hook!='NoHook'] %in% c('TooDeep','ConstantDepth'))
survFloatDead<-Surv(info$lastDay,info$fate %in% c('TooDeep','ConstantDepth','Float'))
survLostDead<-Surv(info$lastDay,info$fate %in% c('TooDeep','ConstantDepth','Lost'))
survLostDeadNoNoHook<-Surv(info$lastDay[info$hook!='NoHook'],info$fate[info$hook!='NoHook'] %in% c('TooDeep','ConstantDepth','Lost'))
km<-survfit(surv~1,conf.type='log-log')
kmFloat<-survfit(survFloatDead~1,conf.type='log-log')
kmLost<-survfit(survLostDead~1,conf.type='log-log')
kmHook<-survfit(surv~hookFac,conf.type='log-log',data=info)
kmHookFloat<-survfit(survFloatDead~hookFac,conf.type='log-log',data=info)
kmHookLost<-survfit(survLostDead~hookFac,conf.type='log-log',data=info)
summary(coxph(survNoNoHook~hook*as.numeric(CCL.notch.to.tip),data=info[info$hook!='NoHook',]))
summary(coxph(survFloatDead~hookFac+as.numeric(CCL.notch.to.tip),data=info))
summary(coxph(survFloatDead~hookFac,data=info))
summary(coxph(survNoNoHook~hook,data=info[info$hook!='NoHook',]))
summary(coxph(survLostDead~hook,data=info))
summary(coxph(survLostDeadNoNoHook~hook,data=info[info$hook!='NoHook',]))

addConfInt<-function(sf,cols){
  for(ii in names(cols)){
    print(ii)
    strataPos<-grep(sprintf('=%s$',ii),names(sf$strata)) # 
    ids<-sum(head(sf$strata,strataPos-1))+1:sf$strata[strataPos]
    x<-c(sf$time[ids],rev(sf$time[ids]))
    y<-c(sf$upper[ids],rev(sf$lower[ids]))
    polygon(x,y,col=cols[ii],border=NA)
  }
  return(NULL)
}
hookColor<-rainbow.lab(length(unique(na.omit(info$hook))),lightScale=0,lightMultiple=.7,alpha=1)
hookColor2<-rainbow.lab(length(unique(na.omit(info$hook))),lightScale=0,lightMultiple=.7,alpha=.1)
names(hookColor)<-names(hookColor2)<-levels(info$hookFac)
pdf('out/kmCurve.pdf')
  plot(km,xlab='Days after tagging',ylab='Proportion surviving',conf.int=TRUE)
  plot(kmHook,xlab='Days after tagging',ylab='Proportion surviving',col=hookColor,lwd=2)
  addConfInt(kmHook,hookColor2)
  legend('bottomright',levels(info$hookFac),col=hookColor,lwd=1,bty='n')
  plot(kmFloat,xlab='Days after tagging',ylab='Proportion surviving (float=death)')
  plot(kmHookFloat,xlab='Days after tagging',ylab='Proportion surviving (float=death)',col=hookColor,lwd=2)
  legend('topright',levels(info$hookFac),col=hookColor,lwd=2,bty='n')
  addConfInt(kmHookFloat,hookColor2)
  plot(kmLost,xlab='Days after tagging',ylab='Proportion surviving (lost tag=death)')
  plot(kmHookLost,xlab='Days after tagging',ylab='Proportion surviving (lost tag=death)',col=hookColor,lwd=2)
  addConfInt(kmHookLost,hookColor2)
  legend('topright',levels(info$hookFac),col=hookColor,lwd=2,bty='n')
dev.off()
