library(survival)
source("~/scripts/R/dna.R")

if(!exists('tagData'))source('readData.R')
info$hookFac<-factor(info$hook)
info$longMono<-factor(ifelse(info$mono>30,'Long mono','Short mono'))
info$obsFac<-factor(info$observer)
surv<-Surv(info$lastDay,info$fate %in% c('TooDeep','ConstantDepth'))
surv60<-Surv(info$lastDay[info$lastDay>60|info$fate %in% c('TooDeep','ConstantDepth')],info$fate[info$lastDay>60|info$fate %in% c('TooDeep','ConstantDepth')] %in% c('TooDeep','ConstantDepth'))
survMono<-Surv(info$lastDay[!is.na(info$mono)],info$fate[!is.na(info$mono)] %in% c('TooDeep','ConstantDepth'))
survObs<-Surv(info$lastDay[!is.na(info$observer)&info$hook!='NoHook'],info$fate[!is.na(info$observer)&info$hook!='NoHook'] %in% c('TooDeep','ConstantDepth'))
survNoNoHook<-Surv(info$lastDay[info$hook!='NoHook'],info$fate[info$hook!='NoHook'] %in% c('TooDeep','ConstantDepth'))
survFloatDead<-Surv(info$lastDay,info$fate %in% c('TooDeep','ConstantDepth','Float'))
survLostDead<-Surv(info$lastDay,info$fate %in% c('TooDeep','ConstantDepth','Lost'))
survLostDeadNoNoHook<-Surv(info$lastDay[info$hook!='NoHook'],info$fate[info$hook!='NoHook'] %in% c('TooDeep','ConstantDepth','Lost'))
km<-survfit(surv~1,conf.type='log-log')
kmFloat<-survfit(survFloatDead~1,conf.type='log-log')
kmLost<-survfit(survLostDead~1,conf.type='log-log')
kmHook<-survfit(surv~hookFac,conf.type='log-log',data=info)
kmHook60<-survfit(surv60~hookFac,conf.type='log-log',data=info[info$lastDay>60|info$fate %in% c('TooDeep','ConstantDepth'),])
kmHookFloat<-survfit(survFloatDead~hookFac,conf.type='log-log',data=info)
kmHookLost<-survfit(survLostDead~hookFac,conf.type='log-log',data=info)
kmMono<-survfit(survMono~longMono,conf.type='log-log',data=info[!is.na(info$mono),])
kmObs<-survfit(survObs~obsFac,conf.type='log-log',data=info[!is.na(info$observer)&info$hook!='NoHook',])
summary(coxph(survNoNoHook~hook*CCL.notch.to.tip,data=info[info$hook!='NoHook',]))
summary(coxph(survFloatDead~hookFac+CCL.notch.to.tip,data=info))
summary(coxph(survFloatDead~hookFac,data=info))
summary(coxph(survNoNoHook~hook,data=info[info$hook!='NoHook',]))
summary(coxph(survLostDead~hook,data=info))
summary(coxph(survLostDeadNoNoHook~hook,data=info[info$hook!='NoHook',]))
summary(coxph(survMono~longMono,data=info[!is.na(info$mono),]))
summary(coxph(survObs~obsFac+hook,data=info[!is.na(info$observer)&info$hook!='NoHook',]))

addConfInt<-function(sf,cols){
  for(ii in names(cols)){
    print(ii)
    strataPos<-grep(sprintf('=%s$',ii),names(sf$strata)) # 
    ids<-sum(head(sf$strata,strataPos-1))+1:sf$strata[strataPos]
    x<-c(sf$time[ids],rev(sf$time[ids]))
    y<-c(sf$upper[ids],rev(sf$lower[ids]))
    polygon(x,y,col=cols[ii],border=NA)
  }
  return(NULL)
}
hookColor<-rainbow.lab(length(unique(na.omit(info$hook))),lightScale=0,lightMultiple=.7,alpha=1)
hookColor2<-rainbow.lab(length(unique(na.omit(info$hook))),lightScale=0,lightMultiple=.7,alpha=.1)
names(hookColor)<-names(hookColor2)<-levels(info$hookFac)

monoColor<-rainbow.lab(2,lightScale=0,lightMultiple=.7,alpha=1,start=2,end=-2.5)
monoColor2<-rainbow.lab(2,lightScale=0,lightMultiple=.7,alpha=.1,start=2,end=-2.5)
names(monoColor)<-names(monoColor2)<-levels(info$longMono)

obsColor<-rainbow.lab(2,lightScale=0,lightMultiple=.7,alpha=1,start=1,end=-1)
obsColor2<-rainbow.lab(2,lightScale=0,lightMultiple=.7,alpha=.1,start=1,end=-1)
names(obsColor)<-names(obsColor2)<-levels(info$obsFac)

pdf('out/finalKm.pdf')
  plot(km,xlab='Days after tagging',ylab='Proportion surviving',conf.int=TRUE)
  plot(kmHook,xlab='Days after tagging',ylab='Proportion surviving',col=hookColor,lwd=2)
  addConfInt(kmHook,hookColor2)
  legend('bottomright',levels(info$hookFac),col=hookColor,lwd=1,bty='n')
  plot(kmMono,xlab='Days after tagging',ylab='Proportion surviving',col=monoColor,lwd=2)
  addConfInt(kmMono,monoColor2)
  legend('bottomright',levels(info$longMono),col=monoColor,lwd=1,bty='n')
  plot(kmObs,xlab='Days after tagging',ylab='Proportion surviving',col=obsColor,lwd=2)
  addConfInt(kmObs,obsColor2)
  legend('bottomright',levels(info$obsFac),col=obsColor,lwd=1,bty='n')
  plot(kmHook60,xlab='Days after tagging',ylab='Proportion surviving',col=hookColor,lwd=2,main='Only turtles over 60 days tracking or inferred dead')
  addConfInt(kmHook60,hookColor2)
  legend('bottomright',levels(info$hookFac),col=hookColor,lwd=1,bty='n')
dev.off()

pdf('out/kmCurve.pdf')
  plot(km,xlab='Days after tagging',ylab='Proportion surviving',conf.int=TRUE)
  plot(kmHook,xlab='Days after tagging',ylab='Proportion surviving',col=hookColor,lwd=2)
  addConfInt(kmHook,hookColor2)
  legend('bottomright',levels(info$hookFac),col=hookColor,lwd=1,bty='n')
  plot(kmFloat,xlab='Days after tagging',ylab='Proportion surviving (float=death)')
  plot(kmHookFloat,xlab='Days after tagging',ylab='Proportion surviving (float=death)',col=hookColor,lwd=2)
  legend('topright',levels(info$hookFac),col=hookColor,lwd=2,bty='n')
  addConfInt(kmHookFloat,hookColor2)
  plot(kmLost,xlab='Days after tagging',ylab='Proportion surviving (lost tag=death)')
  plot(kmHookLost,xlab='Days after tagging',ylab='Proportion surviving (lost tag=death)',col=hookColor,lwd=2)
  addConfInt(kmHookLost,hookColor2)
  legend('topright',levels(info$hookFac),col=hookColor,lwd=2,bty='n')
dev.off()
